project/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('list/', views.List, name='List'),
    path('video/<int:video_id>', views.video, name='video'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('main/', include('main.urls')),
]

project/main/models.py
from django.db import models

# Create your models here.

class youtube(models.Model) :
    video_id = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    publishedAt = models.CharField(max_length=100)
    channelId = models.CharField(max_length=50)
    categoryId = models.CharField(max_length=50)
    trending_date = models.CharField(max_length=50)
    tags = models.CharField(max_length=50)
    view_count = models.CharField(max_length=50)
    likes = models.CharField(max_length=10)
    dislikes = models.CharField(max_length=10)
    comment_count = models.CharField(max_length=10)
    thumbnail_link = models.CharField(max_length=100)
    comments_disabled = models.CharField(max_length=50)
    ratings_disabled = models.CharField(max_length=100)
    description = models.CharField(max_length=200)


class youtube_recent(models.Model) :
    video_id = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    publishedAt = models.CharField(max_length=100)
    channelId = models.CharField(max_length=50)
    categoryId = models.CharField(max_length=50)
    trending_date = models.CharField(max_length=50)
    tags = models.CharField(max_length=50)
    view_count = models.CharField(max_length=50)
    likes = models.CharField(max_length=10)
    dislikes = models.CharField(max_length=10)
    comment_count = models.CharField(max_length=10)
    thumbnail_link = models.CharField(max_length=100)
    comments_disabled = models.CharField(max_length=50)
    ratings_disabled = models.CharField(max_length=100)
    description = models.CharField(max_length=200)

class food(models.Model) :
    food_name = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    classification = models.CharField(max_length=50)
    topic = models.CharField(max_length=50)
    topic_rate = models.CharField(max_length=50)

project/main/views.py
from django.shortcuts import render, redirect
from .models import youtube_recent, food
import pandas as pd
import random
import joblib
import gensim

# Create your views here.
ldamodel = joblib.load('ldamodel.pkl')
dictionary = joblib.load('dictionary.pkl')
# topictable dataframe 생성 함수
def make_topictable_per_doc(ldamodel, corpus):
    topic_table = pd.DataFrame()

    # 몇 번째 문서인지를 의미하는 문서 번호와 해당 문서의 토픽 비중을 한 줄씩 꺼내온다.
    for i, topic_list in enumerate(ldamodel[corpus]):
        doc = topic_list[0] if ldamodel.per_word_topics else topic_list
        doc = sorted(doc, key=lambda x: (x[1]), reverse=True)
        # 각 문서에 대해서 비중이 높은 토픽순으로 토픽을 정렬한다.
        # EX) 정렬 전 0번 문서 : (2번 토픽, 48.5%), (8번 토픽, 25%), (10번 토픽, 5%), (12번 토픽, 21.5%), 
        # Ex) 정렬 후 0번 문서 : (2번 토픽, 48.5%), (8번 토픽, 25%), (12번 토픽, 21.5%), (10번 토픽, 5%)
        # 48 > 25 > 21 > 5 순으로 정렬이 된 것.

        # 모든 문서에 대해서 각각 아래를 수행
        for j, (topic_num, prop_topic) in enumerate(doc): #  몇 번 토픽인지와 비중을 나눠서 저장한다.
            if j == 0:  # 정렬을 한 상태이므로 가장 앞에 있는 것이 가장 비중이 높은 토픽
                topic_table = topic_table.append(pd.Series([int(topic_num), round(prop_topic,4)]), ignore_index=True)
                # 가장 비중이 높은 토픽과, 가장 비중이 높은 토픽의 비중을 저장한다.
            else:
                break
    return(topic_table)

def List(request) :
    context = {}

    if request.method == "GET" :
        food = request.GET.getlist('food')
        while ("" in food) :
            food.remove("")
            print("success")

        context["food"] = food

        value = food
        print(value)
        X = " ".join(value)
        documents_input = []
        keyword_input = X.split()
        print(keyword_input)
        

        documents_input.append(keyword_input)
        corpus_input = [dictionary.doc2bow(text) for text in documents_input]
        topictable_input = make_topictable_per_doc(ldamodel, corpus_input)
        topictable_input.columns = ['topic', 'topic_rate']
        # 입력 키워드에 대한 가장 비중이 높은 토픽과, 가장 비중이 높은 토픽의 비중과, 전체 토픽의 비중 출력
        
        topic_result = topictable_input['topic'][0]
        print(topic_result)
        result = youtube_recent.objects.filter(categoryId=topic_result)[:5]
        print(f"1:{result}")

        context['video'] = result
        print(context['video'])
    

    return render(request, 'main/list.html', context)

def video(request, video_id) :
    video = youtube_recent.objects.filter(id=video_id)

    context = {
        'video' : video
    }

    return render(request, 'main/video.html', context)

project/project/views.py
from django.shortcuts import render, redirect
# Create your views here.

def home(request) :
    return render(request, 'main/home.html')

project/main/templates/main/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/home.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'main/home.js' %}"></script>
</head>
<body>
    <header>
        <div class="headercontainer">
            <a href="{% url 'home' %}" id="font1">Youtube with Food</a>
        </div>
    </header>
    <div class="container">
        <div class="mcontainer">
        <button type="button" class="arrow" id="arrow_left"><img src="{% static 'main/images/btn1.png' %}" width="45"></button>
            <div class="foodcontainer">
                <div id="food_1">
                    <button id="food1" class="food food1" value="food1">구이류, 국&#38;탕류</button>
                    <button id="food2" class="food food1" value="food2">비빔밥&#38;죽류</button>
                    <button id="food3" class="food food1" value="food3">찌개&#38;전골류</button>
                    <button id="food4" class="food food1" value="food4">피자류</button>
                    <button id="food5" class="food food1" value="food5">샌드위치류&#38;버거류</button>
                    <button id="food6" class="food food1" value="food6">치킨류</button>
                    <button id="food7" class="food food1" value="food7">김밥(초밥)류</button>
                    <button id="food8" class="food food1" value="food8">찜류</button>
                </div>
                <div id="food_2">
                    <button id="food8" class="food food2" value="food9">부침류</button>
                    <button id="food9" class="food food2" value="food10">포&#38;회류</button>
                    <button id="food10" class="food food2" value="food11">떡볶이류</button>
                    <button id="food11" class="food food2" value="food12">케이크류</button>
                    <button id="food12" class="food food2" value="food13">복음밥&#38;덮밥류</button>
                    <button id="food13" class="food food2" value="food14">면류</button>
                    <button id="food14" class="food food2" value="food15">튀김류</button>
                </div>
            </div>
            <button type="button" class="arrow" id="arrow_right"><img src="{% static 'main/images/btn2.png' %}" width="45" ></button>
        </div>

        <form method="GET" action="{% url 'main:List' %}">
            <input type="hidden" value="" id="input1" name="food">
            <input type="hidden" value="" id="input2" name="food">
            <input type="hidden" value="" id="input3" name="food">
            <input type="hidden" value="" id="input4" name="food">
            <input type="hidden" value="" id="input5" name="food">
            <input type="hidden" value="" id="input6" name="food">
            <input type="hidden" value="" id="input7" name="food">
            <input type="hidden" value="" id="input8" name="food">
            <input type="hidden" value="" id="input9" name="food">
            <input type="hidden" value="" id="input10" name="food">
            <input type="hidden" value="" id="input11" name="food">
            <input type="hidden" value="" id="input12" name="food">
            <input type="hidden" value="" id="input13" name="food">
            <input type="hidden" value="" id="input14" name="food">
            <div class="btnbox">
                <button id="btn"type="submit">영상추천하기</button>
            </div>
        </form>
    </div>
    
    <footer>
        <div id="footcontainer">
            <p>광주 인공지능 사관학교 해커톤</p>
        </div>
    </footer>

</body>
</html>

project/main/templates/main/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/list.css' %}">
</head>
<body>
    <header>
    <div class="headercontainer">
            <a href="{% url 'home' %}" id="font1">Youtube with Food </a>
    </div>
    </header>

    
    <section id="content">
        <ul>
            <li class="listli">
                <div class="list">
                    <a href="{% url 'main:video' video.0.id %}"><img src=" {{ video.0.thumbnail_link}} " class="img"></a>
                    <div class="info">
                        <p>{{ food.0 }}</p>
                        <a class="title" href="{% url 'main:video' video.0.id %}"> {{ video.0.title }}</a>
                        <p class="like"> 좋아요: {{ video.0.likes }}  싫어요: {{ video.0.dislikes}} </p>
                    </div>
                </div>
            </li>
            <li class="listli">
                <div class="list">
                    <a href="{% url 'main:video' video.1.id %}"><img src=" {{ video.1.thumbnail_link}} " class="img"></a>
                    <div class="info">
                        <a class="title" href="{% url 'main:video' video.1.id %}"> {{ video.1.title }}</a>
                        <p class="like"> 좋아요: {{ video.1.likes }}  싫어요: {{ video.1.dislikes}} </p>
                    </div>
                </div>
            </li>
            <li class="listli">
                <div class="list">
                    <a href="{% url 'main:video' video.2.id %}"><img src=" {{ video.2.thumbnail_link}} " class="img"></a>
                    <div class="info">
                        <a class="title" href="{% url 'main:video' video.2.id %}"> {{ video.2.title }}</a>
                        <p class="like"> 좋아요: {{ video.2.likes }}  싫어요: {{ video.2.dislikes}} </p>
                    </div>
                </div>
            </li>
            <li class="listli">
                <div class="list">
                    <a href="{% url 'main:video' video.3.id %}"><img src=" {{ video.3.thumbnail_link}} " class="img"></a>
                    <div class="info">
                        <a class="title" href="{% url 'main:video' video.3.id %}"> {{ video.3.title }}</a>
                        <p class="like"> 좋아요: {{ video.3.likes }}  싫어요: {{ video.3.dislikes}} </p>
                    </div>
                </div>
            </li>
            <li class="listli">
                <div class="list">
                    <a href="{% url 'main:video' video.4.id %}"><img src=" {{ video.4.thumbnail_link}} " class="img"></a>
                    <div class="info">
                        <a class="title" href="{% url 'main:video' video.4.id %}"> {{ video.4.title }}</a>
                        <p class="like"> 좋아요: {{ video.4.likes }}  싫어요: {{ video.4.dislikes}} </p>
                    </div>
                </div>
            </li>
        </ul>
    </section>


    <footer>
        <div id="footcontainer">
            <p>광주 인공지능 사관학교 해커톤</p>
        </div>
    </footer>

</body>
</html>

project/main/templates/main/video.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/video.css' %}">
</head>
<body>
    <header>
    <div class="headercontainer">
            <a href="{% url 'home' %}" id="font1">Youtube with Food</a>
    </div>
    </header>


    <section>
        <div id="videobox">
            <p id="title"> {{ video.0.title }}</p>
            <object style="height: 450px; width: 800px" id="video">
                <param name="movie" value="http://www.youtube.com/v/{{ video.0.video_id }}" + {{ video.0.video_id }}>
                <param name="allowFullScreen" value="true">
                <param name="allowScriptAccess" value="always">
                 <embed src="http://www.youtube.com/v/{{ video.0.video_id }}"  type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="390">
            </object>
            <div id="info">
                <p class="view"> Views {{ video.0.view_count }}  </p>
                <p class="like"> Likes {{ video.0.likes }}  Dislikes {{ video.0.dislikes }} </p>
                <p class="time"> {{ video.0.publishedAt }} </p>
                <br>
                <br>
                <p class="description"> {{ video.0.description }} </p>
            </div>
        </div>
    </section>


    <footer>
        <div id="footcontainer">
            <p>광주 인공지능 사관학교 해커톤</p>
        </div>
    </footer>

</body>
</html>